### ISSUE TITLE
deployment list output issue

### ISSUE THREAD

**Issue by dsavineau** [Spredzy/ansible-role-rally#2]
On a RHEL system with OSP repos (newton+), the logic behind the creation of the db is not working :
https://gist.github.com/dsavineau/b2bc041a24fa7429cf888632d1d99750

I can see 3 ways to fix this behaviour :
- Use the RC instead of stdout for rally_deployment_list_result during the DB creation
- Drop the first deployment list command (always recreate the db)
- More logic behing db creation (use db create + test sqlite file instead of db recreate)

**Comment by Spredzy** [comment]
@dsavineau I currently use 2. in my configuration. I skipped the task over recreate and recreate the db all the time.

Since this should be pretty ok with the use case of DCI, it might not be acceptable for other use of this module.

So my answer would be to do 1. for now. More logic behind db creation means to understand how our users use rally, some might use the MySQL backend, if there is one, etc...

WDYT ?

**Comment by dsavineau** [comment]
agree we could start with 1 then improve with the different backends
